const placeholder =
  "https://placehold.co/600x400/f8f3ea/B22222?text=Parudeesa+Kitchen";

const menu = [
  // ================= Today's Menu =================

  {
    id: 1,
    title: "Chicken Biriyani",
    category: "Today's Menu",
    price: "80 / 120",
    img: placeholder,
    desc: "Authentic Kerala style chicken biriyani cooked with aromatic spices.",
  },
  {
    id: 2,
    title: "Kanji",
    category: "Today's Menu",
    price: "80",
    img: placeholder,
    desc: "Traditional kerala food.",
  },
  {
    id: 3,
    title: "Meals",
    category: "Today's Menu",
    price: "80",
    img: placeholder,
    desc: "Kerala meals served with delicious curries and side dishes.",
  },
  {
    id: 4,
    title: "Chicken Roast",
    category: "Today's Menu",
    price: "70 / 130",
    img: placeholder,
    desc: "Slow roasted spicy Kerala chicken prepared with fresh spices.",
  },
  {
    id: 5,
    title: "Beef Roast",
    category: "Today's Menu",
    price: "75 / 140",
    img: placeholder,
    desc: "Tender beef roast cooked in authentic Kerala style.",
  },
  {
    id: 6,
    title: "Egg Roast",
    category: "Today's Menu",
    price: "45",
    img: placeholder,
    desc: "Boiled eggs cooked in rich onion tomato masala.",
  },
  {
    id: 7,
    title: "Beef Biriyani",
    category: "Today's Menu",
    price: "140",
    img: placeholder,
    desc: "Flavorful Kerala beef biriyani made with fragrant rice.",
  },
  {
    id: 8,
    title: "Egg Biriyani",
    category: "Today's Menu",
    price: "90",
    img: placeholder,
    desc: "Classic egg biriyani with aromatic Kerala spices.",
  },
  {
    id: 9,
    title: "Beef Noodles",
    category: "Today's Menu",
    price: "150",
    img: placeholder,
    desc: "Wok tossed noodles with juicy beef and vegetables.",
  },
  {
    id: 10,
    title: "Pepper Chicken",
    category: "Today's Menu",
    price: "120",
    img: placeholder,
    desc: "Chicken tossed with freshly crushed black pepper.",
  },
  {
    id: 11,
    title: "Garlic Chicken",
    category: "Today's Menu",
    price: "120",
    img: placeholder,
    desc: "Juicy chicken stir fried with garlic and herbs.",
  },
  {
    id: 12,
    title: "Ginger Chicken",
    category: "Today's Menu",
    price: "120",
    img: placeholder,
    desc: "Fresh ginger flavored chicken with Kerala spices.",
  },
  {
    id: 13,
    title: "Chilly Chicken",
    category: "Today's Menu",
    price: "120",
    img: placeholder,
    desc: "Hot and spicy chicken with Indo-Chinese flavors.",
  },
  {
    id: 14,
    title: "Chicken Fried Rice",
    category: "Today's Menu",
    price: "140",
    img: placeholder,
    desc: "Classic chicken fried rice cooked in a hot wok.",
  },
  {
    id: 15,
    title: "Chicken Noodles",
    category: "Today's Menu",
    price: "140",
    img: placeholder,
    desc: "Fresh noodles tossed with chicken and vegetables.",
  },
  {
    id: 16,
    title: "Beef Fried Rice",
    category: "Today's Menu",
    price: "150",
    img: placeholder,
    desc: "Flavorful fried rice served with tender beef pieces.",
  },

  // ================= Eggs =================

  {
    id: 17,
    title: "Hen Egg (Boiled)",
    category: "Eggs",
    price: "20",
    img: placeholder,
    desc: "Fresh boiled hen egg.",
  },
  {
    id: 18,
    title: "Quail Egg",
    category: "Eggs",
    price: "Market Price",
    img: placeholder,
    desc: "Fresh boiled quail eggs.",
  },
  {
    id: 19,
    title: "Duck Egg",
    category: "Eggs",
    price: "Market Price",
    img: placeholder,
    desc: "Fresh boiled duck egg.",
  },

  // ================= Fresh Juices =================

  {
    id: 20,
    title: "Dragon Fruit Juice",
    category: "Juices",
    price: "100",
    img: placeholder,
    desc: "Fresh dragon fruit juice without preservatives.",
  },
  {
    id: 21,
    title: "Apple Juice",
    category: "Juices",
    price: "90",
    img: placeholder,
    desc: "Freshly blended apple juice.",
  },
  {
    id: 22,
    title: "Mango Juice",
    category: "Juices",
    price: "70",
    img: placeholder,
    desc: "Sweet and refreshing mango juice.",
  },
  {
    id: 23,
    title: "Orange Juice",
    category: "Juices",
    price: "70",
    img: placeholder,
    desc: "Fresh orange juice packed with Vitamin C.",
  },
  {
    id: 24,
    title: "Guava Juice",
    category: "Juices",
    price: "70",
    img: placeholder,
    desc: "Fresh guava juice prepared daily.",
  },
  {
    id: 25,
    title: "Watermelon Juice",
    category: "Juices",
    price: "60",
    img: placeholder,
    desc: "Naturally refreshing watermelon juice.",
  },
  {
    id: 26,
    title: "Papaya Juice",
    category: "Juices",
    price: "70",
    img: placeholder,
    desc: "Healthy papaya juice made from ripe fruits.",
  },
  {
    id: 27,
    title: "Avocado Juice",
    category: "Juices",
    price: "90",
    img: placeholder,
    desc: "Creamy avocado juice blended fresh.",
  },
  {
    id: 28,
    title: "Avil Milk",
    category: "Juices",
    price: "60",
    img: placeholder,
    desc: "Kerala style Avil Milk with banana and nuts.",
  },
  {
    id: 29,
    title: "Fresh Lime Juice",
    category: "Juices",
    price: "25",
    img: placeholder,
    desc: "Refreshing fresh lime juice.",
  },
];

export default menu;
